#!/bin/bash

set -e

STATE="$1"
FILES="$2"

case "$STATE" in
    ArtifactInstall)
	if [ -e "$FILES"/files/FIT_PART ]
	then
		echo "Updating FIT"
        	dd if="$FILES"/files/FIT_PART of=/dev/mmcblk0p3 bs=4MB
	elif [ -e "$FILES"/files/ROOTFS_PART ]
	then 
		echo "Updating RootFs"
	elif [ -e "$FILES"/files/FULL_SYSTEM ]
	then 
		echo "Updating the whole system"
	else 
		echo "Invalid Module"
	fi
	
        ;;
esac
exit 0